name: netex-map

services:
  postgis:
    image: postgis/postgis:18-3.6-alpine
    restart: always
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
    ports:
      - ${DB_HOST_PORT}:5432
    volumes:
      - data-db:/var/lib/postgresql
      - ${DB_CREATE_SCRIPT_HOST_PATH}:/docker-entrypoint-initdb.d/create.sql
    logging:
      driver: local
      options:
        max-size: 25m
        max-file: 4

volumes:
  data-db:
    name: ${DB_VOLUME_NAME}
