name: netex-map

services:
  timetable-db:
    image: postgis/postgis:18-3.6-alpine
    restart: always
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
    ports:
      - ${DB_HOST_PORT}:5432
    volumes:
      - timetable-db:/var/lib/postgresql
      - ${DB_INIT_SCRIPTS_HOST_PATH}:/docker-entrypoint-initdb.d/
    logging:
      driver: local
      options:
        max-size: 25m
        max-file: 4
  graphhopper:
    image: israelhikingmap/graphhopper:11.0
    restart: no
    container_name: ${GRAPHHOPPER_CONTAINER_NAME}
    command: >
      --input ${GRAPHHOPPER_OSM_PBF_CONTAINER_PATH}
    ports:
      - ${GRAPHHOPPER_HOST_PORT}:8989
    volumes:
      - routing-cache:/data
      - ${OSM_PBF_HOST_PATH}:${GRAPHHOPPER_OSM_PBF_CONTAINER_PATH}:ro
    logging:
      driver: local
      options:
        max-size: 25m
        max-file: 4
  overpass-api:
    user: root
    image: wiktorn/overpass-api:0.7.62.7
    restart: always
    container_name: ${OVERPASS_API_CONTAINER_NAME}
    entrypoint: /bin/bash -c "chmod -R 755 /db && /app/docker-entrypoint.sh"
    ports:
      - ${OVERPASS_API_HOST_PORT}:80
    volumes:
      - ${OSM_PBF_HOST_PATH}:${OVERPASS_API_PBF_CONTAINER_PATH}:ro
      - stops-cache:/db
    environment:
      OVERPASS_MODE: init
      OVERPASS_PLANET_URL: file://${OVERPASS_API_PBF_CONTAINER_PATH}
      OVERPASS_PLANET_PREPROCESS: 'mv /db/planet.osm.bz2 /db/planet.osm.pbf && osmium cat ${OVERPASS_API_OSMIUM_FLAGS} -o /db/planet.osm.bz2 /db/planet.osm.pbf && rm /db/planet.osm.pbf'
    logging:
      driver: local
      options:
        max-size: 25m
        max-file: 4
  timetable-api:
    image: timetable-api:${BE_API_VERSION}
    restart: always
    container_name: ${BE_CONTAINER_NAME}
    depends_on:
      - graphhopper
      - timetable-db
    environment:
      JAVA_TOOL_OPTIONS: ${BE_JAVA_TOOL_OPTIONS}
      ROUTING_SERVICE_URL: ${BE_ROUTING_SERVICE_URL}
      SPRING_DATASOURCE_URL: ${BE_SPRING_DATASOURCE_URL}
      MAP_LOD_CITY_LINES_ZOOM_THRESHOLD: ${BE_LOD_CITY_LINES_ZOOM_THRESHOLD}
      SPRING_DATASOURCE_USER: ${DB_ADMIN_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_ADMIN_PASSWORD}
      SERVER_SERVLET_CONTEXT-PATH: ${FE_API_URN}
    ports:
      - ${BE_HOST_PORT}:8080
    volumes:
      - ${BE_NETEX_PUBLIC_LINES_HOST_PATH}:${BE_NETEX_PUBLIC_LINES_CONTAINER_PATH}:ro
      - ${BE_NETEX_CITY_LINES_HOST_PATH}:${BE_NETEX_CITY_LINES_CONTAINER_PATH}:ro
      - ${BE_JRUTIL_GTFS_UNIFIED_EXPORT_HOST_PATH}:${BE_JRUTIL_GTFS_UNIFIED_EXPORT_CONTAINER_PATH}:ro
    command: >
      --import-netex-zip=${BE_NETEX_PUBLIC_LINES_CONTAINER_PATH}
      --import-netex-zip=${BE_NETEX_CITY_LINES_CONTAINER_PATH}
      --import-stops
      --jrutil-gtfs=${BE_JRUTIL_GTFS_UNIFIED_EXPORT_CONTAINER_PATH}
    logging:
      driver: local
      options:
        max-size: 25m
        max-file: 4
  reverse-proxy:
    image: nginx:mainline-alpine3.23-slim
    container_name: ${PROXY_CONTAINER_NAME}
    restart: always
    ports:
      - ${PROXY_HOST_PORT}:80
    volumes:
      - ${PROXY_HTML_HOST_PATH}:/usr/share/nginx/html
      - ${PROXY_CONFIG_HOST_PATH}:/etc/nginx/nginx.conf:ro
      - ${PROXY_CONFIG_TEMPLATES_HOST_PATH}:/etc/nginx/templates/:ro
    environment:
      HTML_CONTAINER_PATH: ${PROXY_HTML_CONTAINER_PATH}
      API_URL: ${BE_CONTAINER_NAME}:8080
      API_URN: ${FE_API_URN}
    logging:
      driver: local
      options:
        max-size: 25m
        max-file: 4

volumes:
  timetable-db:
    name: ${DB_VOLUME_NAME}
  routing-cache:
    name: ${GRAPHHOPPER_VOLUME_NAME}
  stops-cache:
    name: ${OVERPASS_API_VOLUME_NAME}
  sc2:
    name: sc2
