spring:
  datasource:
    url: jdbc:postgresql://localhost:8112/map?reWriteBatchedInserts=true
    username: SuperUser
    password: stronk-pazzward
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 100

decorator:
  datasource:
    datasource-proxy:
      enabled: true
      enable-logging: true
      multiline: true
      count-query: true

logging:
  level:
    # datasource-proxy's listeners live under this package:
    net.ttddyy.dsproxy.listener: INFO
