spring:
  datasource:
    url: jdbc:postgresql://localhost:8112/map?reWriteBatchedInserts=true
    username: SuperUser
    password: stronk-pazzward
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
      org.hibernate:
        flushMode: COMMIT
server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048
