map:
  lod:
    city-lines-zoom-threshold: 12
    min-route-length:
      8: 0.5
      9: 0.4
      10: 0.3
      11: 0.2
      12: 0.1
      13: 0.0
import:
  input-timetable-batch-size: 30
  active-period-line-versions-batch-size: 100
routing:
  service:
    url: http://localhost:8113
stops:
  service:
    url: http://localhost:8114/api
    health-check: /interpreter?data=[out:json];node(2879637);out;
    health-check-tries: 90
    health-check-wait-ms: 30000
spring:
  datasource:
    url: jdbc:postgresql://localhost:8112/timetable?reWriteBatchedInserts=true
    username: SuperUser
    password: stronk-pazzward
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
      org.hibernate:
        flushMode: COMMIT
server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048
